- id: check-puppetfile-dependencies 
  name: Check puppetforge modules 
  description: Ensure forge modules have appropriate dependencies 
  entry: pre_commit_hooks/check-puppetfile-dependencies.py
  language: python
  types: [text]
  args: [--verbose]
